unique_ids:
  assets:
    standard-page.html: DQX77463AA5ZSIX2NKVRMOCM6LPUTUUG
    theme.css: NQR7ZHJ22RX522BNZABR2QB5QGLAVM5B
  forms:
    Form1: C32UQSSAPO6GYXHQJ5EWD6B3S4LTWGVA
  modules: {}
  scripts: {}
  server_modules: {}
